name: Release

on:
  workflow_dispatch:
jobs:
  release-keenrouterwg:
    #needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5
      - name: version
        run: ver=$(jq -r .version < ./src/package.json) && echo "version=$ver" >> $GITHUB_OUTPUT
        id: version
      - name: pwd
        run: pwd
      - name: check current dir
        run: ls
      - name: release
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          artifactErrorsFailBuild: true
          name: ${{ steps.version.outputs.version }}
          tag: nightly-${{ github.sha }}
          artifacts: src/package.json
          body: |
            Changes in this Release
            - First Change
            - Second Change
        #env:
        #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ## if ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
